# Generated by Django 5.0.2 on 2024-03-03 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnameAR', models.CharField(max_length=15, verbose_name='الإسم الشخصي')),
                ('lnameAR', models.CharField(max_length=15, verbose_name='الإسم العائلي')),
                ('fnameLA', models.CharField(max_length=15, verbose_name='First name')),
                ('lnameLA', models.CharField(max_length=15, verbose_name='Last name')),
                ('cnie', models.CharField(max_length=15, unique=True, verbose_name='رقم بطاقة التعريف الوطنية')),
                ('phone', models.CharField(max_length=14, verbose_name='رقم الهاتف')),
                ('ncreation', models.CharField(max_length=30, verbose_name='رقم التسجيل')),
                ('photo_clt', models.ImageField(blank=True, null=True, upload_to='photos/clients/%Y/%m/%d/', verbose_name='الصورة الشخصية')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'ذكر'), (2, 'أنثى')], default=1, verbose_name='الجنس')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'A'), (2, 'A1'), (3, 'B')], default=3, verbose_name='الصنف')),
                ('nationality', models.CharField(default='MAROCAINE', max_length=15, verbose_name='الجنسية')),
                ('nclient', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الزبون')),
                ('date_joined', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_payed', models.BooleanField(default=False, verbose_name='خالص')),
                ('price', models.PositiveIntegerField(default=3000, verbose_name='الثمن الإجمالي')),
                ('placeofbirthAR', models.CharField(max_length=15, verbose_name='مكان الإزدياد')),
                ('dateofbirth', models.DateField(verbose_name='تاريح الإزدياد')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='monitors.monitorprofile', verbose_name='المدرب')),
            ],
            options={
                'verbose_name_plural': 'قائمة الزبناء',
            },
        ),
        migrations.CreateModel(
            name='Controle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretic', models.PositiveIntegerField(default=0, verbose_name='التعليم النظري')),
                ('practical', models.PositiveIntegerField(default=0, verbose_name='التعليم التطبيقي')),
                ('exam_t1_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إمتحان النظري الأول')),
                ('exam_p1_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إمتحان التطبيقي الأول')),
                ('exam_t2_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إمتحان النظري التاني')),
                ('exam_p2_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إمتحان التطبيقي التاني')),
                ('result', models.PositiveIntegerField(choices=[(0, 'ليس بعد'), (1, 'ناجح'), (2, 'راسب')], default=0, verbose_name='النتيجة النهائية')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النتيجة النهائية')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile', verbose_name='الزبون')),
            ],
            options={
                'verbose_name_plural': 'قائمة تدبير مصالح الزبون',
            },
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.PositiveIntegerField(default=0, verbose_name='قيمة الدفعة')),
                ('payement_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفعة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientprofile', verbose_name='المالية')),
            ],
            options={
                'verbose_name_plural': 'قائمة الموارد المالية',
            },
        ),
    ]
